package com.securedoc.ai.utils

import android.content.Context
import com.itextpdf.text.BaseColor
import com.itextpdf.text.Document
import com.itextpdf.text.Element
import com.itextpdf.text.Font
import com.itextpdf.text.Paragraph
import com.itextpdf.text.pdf.PdfWriter
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object PdfExporter {

    fun exportToPdf(
        context: Context,
        documentType: String,
        confidence: Double,
        scannedText: String,
        summary: String
    ): Boolean {  // ← Thay từ Uri? thành Boolean
        return try {
            // Tạo file PDF
            val fileName = "Document_${System.currentTimeMillis()}.pdf"
            val file = File(context.cacheDir, fileName)

            // Tạo document
            val document = Document()
            PdfWriter.getInstance(document, FileOutputStream(file))
            document.open()

            // Fonts
            val titleFont = Font(Font.FontFamily.HELVETICA, 18f, Font.BOLD)
            val headingFont = Font(Font.FontFamily.HELVETICA, 14f, Font.BOLD)
            val normalFont = Font(Font.FontFamily.HELVETICA, 12f)
            val greyFont = Font(Font.FontFamily.HELVETICA, 10f)
            greyFont.color = BaseColor.GRAY

            // Title
            document.add(Paragraph("\n"))
            val title = Paragraph("SCAN DOCUMENT REPORT", titleFont)
            title.alignment = Element.ALIGN_CENTER
            document.add(title)

            // Timestamp
            val sdf = SimpleDateFormat("dd/MM/yyyy HH:mm:ss", Locale("vi", "VN"))
            val timestamp = Paragraph(sdf.format(Date()), greyFont)
            timestamp.alignment = Element.ALIGN_CENTER
            document.add(timestamp)
            document.add(Paragraph("\n"))

            // Classification Info
            document.add(Paragraph("PHÂN LOẠI TÀI LIỆU", headingFont))
            document.add(Paragraph("Loại: $documentType", normalFont))
            document.add(Paragraph("Độ tin cậy: ${(confidence * 100).toInt()}%", normalFont))
            document.add(Paragraph("\n"))

            // Scanned Text
            document.add(Paragraph("VĂN BẢN GỐC", headingFont))
            document.add(Paragraph(scannedText, normalFont))
            document.add(Paragraph("\n"))

            // Summary
            document.add(Paragraph("THÔNG TIN TRÍCH XUẤT", headingFont))
            document.add(Paragraph(summary, normalFont))
            document.add(Paragraph("\n"))

            // Footer
            val footer = Paragraph("Generated by SecureDocAI", greyFont)
            footer.alignment = Element.ALIGN_CENTER
            document.add(footer)

            document.close()

            android.util.Log.d("PdfExporter", "✅ PDF saved to: ${file.absolutePath}")
            true  // ← Return true nếu thành công

        } catch (e: Exception) {
            android.util.Log.e("PdfExporter", "❌ Error: ${e.message}")
            e.printStackTrace()
            false  // ← Return false nếu lỗi
        }
    }
}